/**
 * This file was auto-generated by frontend/scripts/generate-api-operations.mjs.
 * Do not make direct changes to the file.
 */

import type { operations } from "./schema";

/**
 * A request transport compatible with the existing `apiRequest` in
 * `lib/api/client.ts` and `lib/api/server.ts`: takes a path and options,
 * returns `{ status, data }`. `Options` is inferred from whichever concrete
 * transport is passed at the call site (`RequestOptions` for the browser
 * client, `ServerRequestOptions` for the server client), so this file never
 * imports or duplicates either of those interfaces.
 */
export type ApiTransport<Options extends { method?: string } = { method?: string }> = <T>(
  path: string,
  options?: Options,
) => Promise<{ status: number; data: T }>;

/**
 * Interpolates a templated OpenAPI path (e.g. "/api/v1/projects/{project_id}")
 * with the given parameter values. Every value is URL-encoded, a missing or
 * nullish value throws before any request is made, and no unresolved
 * "{parameter}" placeholder can ever reach the transport.
 */
export function interpolatePath(
  template: string,
  parameters: Record<string, string | number | boolean | null | undefined>,
): string {
  const resolved = template.replace(/\{([^}]+)\}/g, (_match, name: string) => {
    if (!(name in parameters)) {
      throw new Error(`Missing required path parameter: "${name}"`);
    }
    const value = parameters[name];
    if (value === undefined || value === null) {
      throw new Error(`Missing required path parameter: "${name}"`);
    }
    return encodeURIComponent(String(value));
  });

  const unresolved = resolved.match(/\{[^}]*\}/);
  if (unresolved) {
    throw new Error(`Unresolved path parameter placeholder: "${unresolved[0]}"`);
  }

  return resolved;
}

export const projectGetOperation = {
  operationId: "project_get",
  method: "GET",
  path: "/api/v1/projects/{project_id}",
} as const;

export async function projectGet<Options extends { method?: string } = { method?: string }>(
  request: ApiTransport<Options>,
  args: {
    path: NonNullable<operations["project_get"]["parameters"]["path"]>;
    options?: Options;
  },
): Promise<operations["project_get"]["responses"]["200"]["content"]["application/json"]> {
  // Path parameters are interpolated into the runtime URL before the
  // request is made, so a caller can never send an unresolved
  // "{parameter}" placeholder or bypass validation of a required value.
  // The caller's own options are spread first, then `method` is always
  // forced to this operation's declared method afterward, applied
  // uniformly with every other generated operation.
  const resolvedPath = interpolatePath(projectGetOperation.path, args.path);
  const response = await request<operations["project_get"]["responses"]["200"]["content"]["application/json"]>(resolvedPath, {
    ...args.options,
    method: projectGetOperation.method,
  } as Options);
  return response.data;
}
