/**
 * This file was auto-generated by frontend/scripts/generate-api-operations.mjs.
 * Do not make direct changes to the file.
 */

import type { operations } from "./schema";

/**
 * A request transport compatible with the existing `apiRequest` in
 * `lib/api/client.ts` and `lib/api/server.ts`: takes a path and options,
 * returns `{ status, data }`. `Options` is inferred from whichever concrete
 * transport is passed at the call site (`RequestOptions` for the browser
 * client, `ServerRequestOptions` for the server client), so this file never
 * imports or duplicates either of those interfaces.
 */
export type ApiTransport<Options extends { method?: string } = { method?: string }> = <T>(
  path: string,
  options?: Options,
) => Promise<{ status: number; data: T }>;

/**
 * Interpolates a templated OpenAPI path (e.g. "/api/v1/projects/{project_id}")
 * with the given parameter values. Every value is URL-encoded, a missing or
 * nullish value throws before any request is made, and no unresolved
 * "{parameter}" placeholder can ever reach the transport.
 */
export function interpolatePath(
  template: string,
  parameters: Record<string, string | number | boolean | null | undefined>,
): string {
  const resolved = template.replace(/\{([^}]+)\}/g, (_match, name: string) => {
    if (!(name in parameters)) {
      throw new Error(`Missing required path parameter: "${name}"`);
    }
    const value = parameters[name];
    if (value === undefined || value === null) {
      throw new Error(`Missing required path parameter: "${name}"`);
    }
    return encodeURIComponent(String(value));
  });

  const unresolved = resolved.match(/\{[^}]*\}/);
  if (unresolved) {
    throw new Error(`Unresolved path parameter placeholder: "${unresolved[0]}"`);
  }

  return resolved;
}

/**
 * Merges generated request fields after caller options so contract-owned
 * method and body values cannot be overridden.
 */
function mergeRequestOptions<
  Options extends { method?: string },
  Overrides extends { method: string },
>(options: Options | undefined, overrides: Overrides): Options & Overrides {
  return Object.assign({}, options, overrides);
}

export const healthGetOperation = {
  operationId: "health_get",
  method: "GET",
  path: "/health",
} as const;

export async function healthGet<Options extends { method?: string } = { method?: string }>(
  request: ApiTransport<Options>,
  options?: Options,
): Promise<operations["health_get"]["responses"]["200"]["content"]["application/json"]> {
  // The caller's own options are spread first, then `method` is always
  // forced to this operation's declared method afterward, so a caller can
  // never override the contract's HTTP method through `options` — applied
  // uniformly for every operation, GET included, so generated metadata and
  // runtime execution can never disagree.
  const response = await request<operations["health_get"]["responses"]["200"]["content"]["application/json"]>(healthGetOperation.path, {
    ...options,
    method: healthGetOperation.method,
  } as Options);
  return response.data;
}

export const projectCreateOperation = {
  operationId: "project_create",
  method: "POST",
  path: "/api/v1/projects",
} as const;

export async function projectCreate<Options extends { method?: string } = { method?: string }>(
  request: ApiTransport<Options>,
  body: NonNullable<operations["project_create"]["requestBody"]>["content"]["application/json"],
  options?: Options,
): Promise<operations["project_create"]["responses"]["201"]["content"]["application/json"]> {
  // The caller's own options are spread first, then `method` is always
  // forced to this operation's declared method afterward, so a caller can
  // never override the contract's HTTP method through `options` — applied
  // uniformly for every operation, GET included, so generated metadata and
  // runtime execution can never disagree.
  const response = await request<operations["project_create"]["responses"]["201"]["content"]["application/json"]>(projectCreateOperation.path, mergeRequestOptions(options, {
    body,
    method: projectCreateOperation.method,
  }));
  return response.data;
}

export const projectUpdateOperation = {
  operationId: "project_update",
  method: "PATCH",
  path: "/api/v1/projects/{project_id}",
} as const;

export async function projectUpdate<Options extends { method?: string } = { method?: string }>(
  request: ApiTransport<Options>,
  args: {
    path: NonNullable<operations["project_update"]["parameters"]["path"]>;
    body: NonNullable<operations["project_update"]["requestBody"]>["content"]["application/json"];
    options?: Options;
  },
): Promise<operations["project_update"]["responses"]["200"]["content"]["application/json"]> {
  // Path parameters are interpolated into the runtime URL before the
  // request is made, so a caller can never send an unresolved
  // "{parameter}" placeholder or bypass validation of a required value.
  // The caller's own options are spread first, then `method` is always
  // forced to this operation's declared method afterward, applied
  // uniformly with every other generated operation.
  const resolvedPath = interpolatePath(projectUpdateOperation.path, args.path);
  const response = await request<operations["project_update"]["responses"]["200"]["content"]["application/json"]>(resolvedPath, mergeRequestOptions(args.options, {
    body: args.body,
    method: projectUpdateOperation.method,
  }));
  return response.data;
}
